package constants

import "gitlab.com/snap-clickstaff/torque-go/lib/meta"

const (
	ErrorCodeSuccess       = meta.ErrorCode("success")
	ErrorCodeUnknown       = meta.ErrorCode("error_unknown")
	ErrorCodeSystem        = meta.ErrorCode("error_system")
	ErrorCodeInvalidParams = meta.ErrorCode("error_invalid_params")
	ErrorCodeInvalidData   = meta.ErrorCode("error_invalid_data")
	ErrorCodeDataNotFound  = meta.ErrorCode("error_data_not_found")
	ErrorCodeDataExists    = meta.ErrorCode("error_data_exists")
	ErrorCodeAuth          = meta.ErrorCode("error_auth")

	ErrorCodeAddress                          = meta.ErrorCode("error_address")
	ErrorCodeAmount                           = meta.ErrorCode("error_amount")
	ErrorCodeAmountTooHigh                    = meta.ErrorCode("error_amount_too_high")
	ErrorCodeAmountTooHighWithValue           = meta.ErrorCode("error_amount_too_high_with_value")
	ErrorCodeAmountTooLow                     = meta.ErrorCode("error_amount_too_low")
	ErrorCodeAmountTooLowWithValue            = meta.ErrorCode("error_amount_too_low_with_value")
	ErrorCodeAuthInput                        = meta.ErrorCode("error_auth_input")
	ErrorCodeBalanceNotEnough                 = meta.ErrorCode("error_balance_not_enough")
	ErrorCodeBannedCountry                    = meta.ErrorCode("error_banned_country")
	ErrorCodeBlockchainBalanceNotEnoughForFee = meta.ErrorCode("error_blockchain_balance_not_enough_for_fee")
	ErrorCodeChannelConversionOutOfCoin       = meta.ErrorCode("error_channel_conversion_out_of_coin")
	ErrorCodeChannelNotAvailable              = meta.ErrorCode("error_channel_not_available")
	ErrorCodeCurrency                         = meta.ErrorCode("error_currency")
	ErrorCodeDobInvalid                       = meta.ErrorCode("error_dob_invalid")
	ErrorCodeEmailInvalid                     = meta.ErrorCode("error_email_invalid")
	ErrorCodeEmailNotSent                     = meta.ErrorCode("error_email_not_sent")
	ErrorCodeFeatureNotSupport                = meta.ErrorCode("error_feature_not_support")
	ErrorCodeKycRequired                      = meta.ErrorCode("error_kyc_required")
	ErrorCodeKycRequestInvalidStatus          = meta.ErrorCode("error_kyc_request_invalid_status")
	ErrorCodeKycUserBlacklist                 = meta.ErrorCode("error_kyc_user_blacklist")
	ErrorCodeOrderConcurrent                  = meta.ErrorCode("error_order_concurrent")
	ErrorCodeOrderDuplicated                  = meta.ErrorCode("error_order_duplicated")
	ErrorCodeOrderInvalid                     = meta.ErrorCode("error_order_invalid")
	ErrorCodeOrderNotFound                    = meta.ErrorCode("error_order_not_found")
	ErrorCodeOrderStatus                      = meta.ErrorCode("error_order_status")
	ErrorCodeUserActionLocked                 = meta.ErrorCode("error_user_action_locked")
	ErrorCodeUserNotFound                     = meta.ErrorCode("error_user_not_found")
	ErrorCodeUserSubmittedOverLimit           = meta.ErrorCode("error_user_submitted_over_limit")
)

var (
	ErrorUnknown       = meta.NewGeneralError(ErrorCodeUnknown)
	ErrorSystem        = meta.NewGeneralError(ErrorCodeSystem)
	ErrorInvalidParams = meta.NewGeneralError(ErrorCodeInvalidParams)
	ErrorInvalidData   = meta.NewGeneralError(ErrorCodeInvalidData)
	ErrorDataNotFound  = meta.NewGeneralError(ErrorCodeDataNotFound)
	ErrorDataExists    = meta.NewGeneralError(ErrorCodeDataExists)
	ErrorAuth          = meta.NewGeneralError(ErrorCodeAuth)

	ErrorAddress                          = meta.NewGeneralError(ErrorCodeAddress)
	ErrorAmount                           = meta.NewGeneralError(ErrorCodeAmount)
	ErrorAmountTooHigh                    = meta.NewGeneralError(ErrorCodeAmountTooHigh)
	ErrorAmountTooHighWithValue           = meta.NewGeneralError(ErrorCodeAmountTooHighWithValue)
	ErrorAmountTooLow                     = meta.NewGeneralError(ErrorCodeAmountTooLow)
	ErrorAmountTooLowWithValue            = meta.NewGeneralError(ErrorCodeAmountTooLowWithValue)
	ErrorAuthInput                        = meta.NewGeneralError(ErrorCodeAuthInput)
	ErrorBalanceNotEnough                 = meta.NewGeneralError(ErrorCodeBalanceNotEnough)
	ErrorBannedCountry                    = meta.NewGeneralError(ErrorCodeBannedCountry)
	ErrorBlockchainBalanceNotEnoughForFee = meta.NewGeneralError(ErrorCodeBlockchainBalanceNotEnoughForFee)
	ErrorChannelConversionOutOfCoin       = meta.NewGeneralError(ErrorCodeChannelConversionOutOfCoin)
	ErrorChannelNotAvailable              = meta.NewGeneralError(ErrorCodeChannelNotAvailable)
	ErrorCurrency                         = meta.NewGeneralError(ErrorCodeCurrency)
	ErrorDobInvalid                       = meta.NewGeneralError(ErrorCodeDobInvalid)
	ErrorEmailInvalid                     = meta.NewGeneralError(ErrorCodeEmailInvalid)
	ErrorEmailNotSent                     = meta.NewGeneralError(ErrorCodeEmailNotSent)
	ErrorFeatureNotSupport                = meta.NewGeneralError(ErrorCodeFeatureNotSupport)
	ErrorKycRequired                      = meta.NewGeneralError(ErrorCodeKycRequired)
	ErrorKycRequestInvalidStatus          = meta.NewGeneralError(ErrorCodeKycRequestInvalidStatus)
	ErrorKycUserBlacklist                 = meta.NewGeneralError(ErrorCodeKycUserBlacklist)
	ErrorOrderConcurrent                  = meta.NewGeneralError(ErrorCodeOrderConcurrent)
	ErrorOrderDuplicated                  = meta.NewGeneralError(ErrorCodeOrderDuplicated)
	ErrorOrderInvalid                     = meta.NewGeneralError(ErrorCodeOrderInvalid)
	ErrorOrderNotFound                    = meta.NewGeneralError(ErrorCodeOrderNotFound)
	ErrorOrderStatus                      = meta.NewGeneralError(ErrorCodeOrderStatus)
	ErrorUserActionLocked                 = meta.NewGeneralError(ErrorCodeUserActionLocked)
	ErrorUserNotFound                     = meta.NewGeneralError(ErrorCodeUserNotFound)
	ErrorUserSubmittedOverLimit           = meta.NewGeneralError(ErrorCodeUserSubmittedOverLimit)
)
